
const constants = {
  ADD_TODO: "ADD_TODO",
  REMOVE_TODO: "REMOVE_TODO",
  SET_VISIBILITY_FILTER: "SET_VISIBILITY_FILTER",
  SHOW_ACTIVE: "SHOW_ACTIVE",
  SHOW_ALL: "SHOW_ALL",
  SHOW_COMPLETED: "SHOW_COMPLETED",
  TOGGLE_TODO: "TOGGLE_TODO",

};

export default constants;
